force-app/main/default/objects/PrintSerialNumber__c/PrintSerialNumber__c.object-meta.xml
<CustomObject>
    <label>印刷連番</label>
    <nameField>
        <label>印刷連番</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrintSerialNumber__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>カスタマーセンターコールデータ</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>印刷連番</relationshipLabel>
    <relationshipName>PrintSerialNumber</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/CommencementInsuranceWareki__c.field-meta.xml
<CustomField>
    <fullName>CommencementInsuranceWareki__c</fullName>
    <label>保険始期（和暦）</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/Contract_InformationId__c.field-meta.xml
<CustomField>
    <fullName>Contract_InformationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約情報</label>
    <referenceTo>Contract_Information__c</referenceTo>
    <relationshipLabel>印刷連番</relationshipLabel>
    <relationshipName>PrintSerialNumber</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodA__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodA__c</fullName>
    <label>(Aプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodB__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodB__c</fullName>
    <label>(Bプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodC__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodC__c</fullName>
    <label>(Cプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodA__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodA__c</fullName>
    <label>新払込方法（Aプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodB__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodB__c</fullName>
    <label>新払込方法（Bプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodC__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodC__c</fullName>
    <label>新払込方法（Cプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationA__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationA__c</fullName>
    <label>(Aプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationB__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationB__c</fullName>
    <label>(Bプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationC__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationC__c</fullName>
    <label>(Cプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PdfFilePath__c.field-meta.xml
<CustomField>
    <fullName>PdfFilePath__c</fullName>
    <label>PDFファイルパス名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PolicyBranchNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyBranchNumber__c</fullName>
    <label>証券番号枝番</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>証券番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/ProcName__c.field-meta.xml
<CustomField>
    <fullName>ProcName__c</fullName>
    <label>処理名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeA__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeA__c</fullName>
    <label>(Aプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeB__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeB__c</fullName>
    <label>(Bプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeC__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeC__c</fullName>
    <label>(Cプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeA__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeA__c</fullName>
    <label>(Aプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeB__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeB__c</fullName>
    <label>(Bプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeC__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeC__c</fullName>
    <label>(Cプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TransferDate__c.field-meta.xml
<CustomField>
    <fullName>TransferDate__c</fullName>
    <label>異動日</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/OnlineID__c.field-meta.xml
<CustomField>
    <fullName>OnlineID__c</fullName>
    <label>代理店オンラインID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/OnlinePW__c.field-meta.xml
<CustomField>
    <fullName>OnlinePW__c</fullName>
    <label>代理店オンラインPW</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OnlinePrintProcController.cls
public with sharing class OnlinePrintProcController{

    @AuraEnabled(cacheable=true)
    public static List<User> getUserOnlineInfo(){

        String userId = userinfo.getUserId();

        List<User> users= [
                SELECT
                    Id,
                    OnlineID__c , OnlinePW__c
                FROM
                    User
                WHERE
                    Id = :userId
                LIMIT 1
        ];

        return users;
    }

    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getPrintDatas( String caseId){

        List<PrintSerialNumber__c> printSerialNumbers = [
            SELECT
                Id, Name, ProcName__c,
                CreatedDate, CreatedById, 
                PolicyNumber__c, PolicyBranchNumber__c, 
                CommencementInsuranceWareki__c, 
                InsurancePeriodA__c, InsurancePeriodB__c, InsurancePeriodC__c, 
                PaymentMethodA__c, PaymentMethodB__c, PaymentMethodC__c, 
                PaymentMethodTranslationA__c, PaymentMethodTranslationB__c, PaymentMethodTranslationC__c, 
                SumInsuranceFeeA__c, SumInsuranceFeeB__c, SumInsuranceFeeC__c, 
                TotalInsuranceFeeA__c, TotalInsuranceFeeB__c, TotalInsuranceFeeC__c, 
                PdfFilePath__c, Contract_InformationId__c, CaseId__c ,TransferDate__c
            FROM PrintSerialNumber__c
            WHERE
                CaseId__c = :caseId
        ];

        List<Map<String, String>> cList = new List<Map<String, String>>();

        // 受付日時がGMT表記になってしまうため、変換処理
        for (PrintSerialNumber__c rec : printSerialNumbers) {
            Map<String, String> cMap = new Map<String, String>();
            cMap.put('ProcName__c', rec.ProcName__c);
            cMap.put('Id', String.valueOf(rec.Id));
            cMap.put('Name', rec.Name);
            cMap.put('PolicyNumber__c', rec.PolicyNumber__c);
            String ProcDate = rec.Name.left(1) == 'B' || rec.Name.left(1) == 'K' ? rec.TransferDate__c : rec.CommencementInsuranceWareki__c;
            cMap.put('ProcDate', ProcDate);
            cMap.put('CreatedDate', String.valueOf(rec.CreatedDate));
            if(String.isBlank(rec.InsurancePeriodA__c) && String.isBlank(rec.InsurancePeriodB__c) && String.isBlank(rec.InsurancePeriodC__c)){
                cList.add(cMap);
            }else{
                if(!String.isBlank(rec.InsurancePeriodA__c)){
                    Map<String, String> cMapA = cMap.clone();
                    cMapA.put('Plan', 'A');
                    cMapA.put('InsurancePeriod', rec.InsurancePeriodA__c);
                    cMapA.put('InsuranceFee', String.valueOf(rec.SumInsuranceFeeA__c)); 
                    cMapA.put('TotalInsuranceFee', String.valueOf(rec.TotalInsuranceFeeA__c)); 
                    cMapA.put('PaymentMethodTranslation', rec.PaymentMethodTranslationA__c); 
                    cList.add(cMapA);
                }
                
                if(!String.isBlank(rec.InsurancePeriodB__c)){
                    Map<String, String> cMapB = cMap.clone();
                    cMapB.put('Plan', 'B');
                    cMapB.put('InsurancePeriod', rec.InsurancePeriodB__c);
                    cMapB.put('InsuranceFee', String.valueOf(rec.SumInsuranceFeeB__c)); 
                    cMapB.put('TotalInsuranceFee', String.valueOf(rec.TotalInsuranceFeeB__c)); 
                    cMapB.put('PaymentMethodTranslation', rec.PaymentMethodTranslationB__c); 
                    cList.add(cMapB);
                }
                
                if(!String.isBlank(rec.InsurancePeriodC__c)){
                    Map<String, String> cMapC = cMap.clone();
                    cMapC.put('Plan', 'C');
                    cMapC.put('InsurancePeriod', rec.InsurancePeriodC__c);
                    cMapC.put('InsuranceFee', String.valueOf(rec.SumInsuranceFeeC__c)); 
                    cMapC.put('TotalInsuranceFee', String.valueOf(rec.TotalInsuranceFeeC__c));
                    cMapC.put('PaymentMethodTranslation', rec.PaymentMethodTranslationC__c); 
                    cList.add(cMapC);
                }
            }
        }

        return cList;
    }

}