force-app/main/default/objects/Case/fields/CommencementInsuranceWareki__c.field-meta.xml
<CustomField>
    <fullName>CommencementInsuranceWareki__c</fullName>
    <label>保険始期（和暦）（代理店報告リスト用）</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractInformationId__c.field-meta.xml
<CustomField>
    <fullName>ContractInformationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約情報</label>
    <referenceTo>Contract_Information__c</referenceTo>
    <relationshipLabel>カスタマーセンターコールデータ</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/NoFollow_UpRequired__c.field-meta.xml
<CustomField>
    <fullName>NoFollow_UpRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>フォロー不要</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>証券番号</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PrintSerialNumber__c.field-meta.xml
<CustomField>
    <fullName>PrintSerialNumber__c</fullName>
    <label>印刷連番</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/PrintSerialNumber__c.object-meta.xml
<CustomObject>
    <label>印刷連番</label>
    <nameField>
        <label>印刷連番</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrintSerialNumber__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>カスタマーセンターコールデータ</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>印刷連番</relationshipLabel>
    <relationshipName>PrintSerialNumber</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/CaseLastModifiedByName__c.field-meta.xml
<CustomField>
    <fullName>CaseLastModifiedByName__c</fullName>
    <label>コールデータ更新者</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/CommencementInsuranceWareki__c.field-meta.xml
<CustomField>
    <fullName>CommencementInsuranceWareki__c</fullName>
    <label>保険始期（和暦）</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/Contract_InformationId__c.field-meta.xml
<CustomField>
    <fullName>Contract_InformationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約情報</label>
    <referenceTo>Contract_Information__c</referenceTo>
    <relationshipLabel>印刷連番</relationshipLabel>
    <relationshipName>PrintSerialNumber</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodA__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodA__c</fullName>
    <label>(Aプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodB__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodB__c</fullName>
    <label>(Bプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodC__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodC__c</fullName>
    <label>(Cプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodA__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodA__c</fullName>
    <label>新払込方法（Aプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodB__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodB__c</fullName>
    <label>新払込方法（Bプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodC__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodC__c</fullName>
    <label>新払込方法（Cプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationA__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationA__c</fullName>
    <label>(Aプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationB__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationB__c</fullName>
    <label>(Bプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationC__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationC__c</fullName>
    <label>(Cプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PdfFilePath__c.field-meta.xml
<CustomField>
    <fullName>PdfFilePath__c</fullName>
    <label>PDFファイルパス名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PolicyBranchNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyBranchNumber__c</fullName>
    <label>証券番号枝番</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>証券番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/ProcName__c.field-meta.xml
<CustomField>
    <fullName>ProcName__c</fullName>
    <label>処理名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeA__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeA__c</fullName>
    <label>(Aプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeB__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeB__c</fullName>
    <label>(Bプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeC__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeC__c</fullName>
    <label>(Cプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeA__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeA__c</fullName>
    <label>(Aプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeB__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeB__c</fullName>
    <label>(Bプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeC__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeC__c</fullName>
    <label>(Cプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TransferDate__c.field-meta.xml
<CustomField>
    <fullName>TransferDate__c</fullName>
    <label>異動日</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetOnlinePrintProcRest.cls
@RestResource(urlMapping='/GetPrintDataInfo')
global without Sharing class GetOnlinePrintProcRest{
    @HttpPost
    global static void processIncomingData() {
        // Retrieve POST data
        RestRequest req = RestContext.request;
        String reqString = req.requestBody.toString();
        //
        RestResponse res = RestContext.response;
        res.statusCode = 400;
        res.addHeader('Content-Type', 'application/json');

        //If POST data is blank, redirect immediately
        if (reqString == null || String.isBlank(reqString)) {
            return;
        }
        System.debug('POSTデータ: ' + reqString);
        Request params = (Request) System.JSON.deserialize(reqString, Request.class);
        if(String.isBlank(params.gyoumu_id)){
            //エラー
            return;
        }
        String gyoumu_Id = params.gyoumu_Id.left(15);
        String proc_code = params.gyoumu_Id.right(2);
        if(gyoumu_Id.left(3) <> '500'){
            return;
        }
        Case targetCase = [Select Id, ContractInformationId__c,
            ExpectedShippingDate_Latest__c,
            ReturnFollow_UpDate_Latest__c,
            NoFollow_UpRequired__c,
            ShipmentRequired__c,
            LastmodifiedById,
            LastmodifiedBy.Name
            From Case Where Id = :gyoumu_Id limit 1];
        if(targetCase == null){
            return;
        }
        Attachment att= new Attachment();
        att.parentId = targetCase.Id;
        att.Body = EncodingUtil.Base64Decode(params.pdfFiledata);
        att.Name = params.ccRnki_InstRnbn + params.pdfFilePath.right(params.pdfFilePath.length() - params.pdfFilePath.lastIndexOf('/') -1);
        insert att;
        PrintSerialNumber__c print = new PrintSerialNumber__c();
        print.CaseId__c = targetCase.Id;//ケースId
        print.Contract_InformationId__c = targetCase.ContractInformationId__c;//契約情報
        print.Name = params.ccRnki_InstRnbn;//印刷連番
        if(params.ccRnki_SyknNo.contains('-')){
            list<String> syknNos = params.ccRnki_SyknNo.split('-');
            print.PolicyNumber__c = syknNos[0];//証券番号
            print.PolicyBranchNumber__c = syknNos[1];//証券番号枝番
        }else{
            print.PolicyNumber__c = params.ccRnki_SyknNo;//証券番号
            print.PolicyBranchNumber__c = params.ccRnki_SyknNoEdbn;//証券番号枝番
        }
        if(String.isBlank(params.ccRnki_IduD)){
            print.CommencementInsuranceWareki__c = params.ccRnki_HknSiki;//保険始期
        }else{
            print.CommencementInsuranceWareki__c = params.ccRnki_IduD;//保険始期
            print.TransferDate__c = params.ccRnki_IduD;//異動日
        }
        print.InsurancePeriodA__c = params.ccRnki_P1_HknSyki;//(Aプラン)保険終期
        print.InsurancePeriodB__c = params.ccRnki_P2_HknSyki;//(Bプラン)保険終期
        print.InsurancePeriodC__c = params.ccRnki_P3_HknSyki;//(Cプラン)保険終期
        print.PaymentMethodA__c = params.p1_HrikmHuhu;//(Aプラン)払込方法
        print.PaymentMethodB__c = params.p2_HrikmHuhu;//(Bプラン)払込方法
        print.PaymentMethodC__c = params.p3_HrikmHuhu;//(Cプラン)払込方法
        print.PaymentMethodTranslationA__c = params.ccRnki_P1_HrikmHuhu;//(Aプラン)払込方法翻訳
        print.PaymentMethodTranslationB__c = params.ccRnki_P2_HrikmHuhu;//(Bプラン)払込方法翻訳
        print.PaymentMethodTranslationC__c = params.ccRnki_P3_HrikmHuhu;//(Cプラン)払込方法翻訳
        
        if(String.isBlank(params.ccRnki_GukiHknr)){
            print.SumInsuranceFeeA__c = String.isBlank(params.ccRnki_P1_GukiHknr) ? 0 : Decimal.valueOf(params.ccRnki_P1_GukiHknr.replace(',', ''));//(Aプラン)合計保険料
            print.SumInsuranceFeeB__c = String.isBlank(params.ccRnki_P2_GukiHknr) ? 0 : Decimal.valueOf(params.ccRnki_P2_GukiHknr.replace(',', ''));//(Bプラン)合計保険料
            print.SumInsuranceFeeC__c = String.isBlank(params.ccRnki_P3_GukiHknr) ? 0 : Decimal.valueOf(params.ccRnki_P3_GukiHknr.replace(',', ''));//(Cプラン)合計保険料
            print.TotalInsuranceFeeA__c = String.isBlank(params.ccRnki_P1_SuGkHknr) ? 0 : Decimal.valueOf(params.ccRnki_P1_SuGkHknr.replace(',', ''));//(Aプラン)総額保険料
            print.TotalInsuranceFeeB__c = String.isBlank(params.ccRnki_P2_SuGkHknr) ? 0 : Decimal.valueOf(params.ccRnki_P2_SuGkHknr.replace(',', ''));//(Bプラン)総額保険料
            print.TotalInsuranceFeeC__c = String.isBlank(params.ccRnki_P3_SuGkHknr) ? 0 : Decimal.valueOf(params.ccRnki_P3_SuGkHknr.replace(',', ''));//(Cプラン)総額保険料
        }else{
            print.SumInsuranceFeeA__c = String.isBlank(params.ccRnki_GukiHknr) ? 0 : Decimal.valueOf(params.ccRnki_GukiHknr.replace(',', ''));//(Aプラン)合計保険料
        }
        print.PdfFilePath__c = params.pdfFilePath;//PDFファイルパス名
        print.CaseLastModifiedByName__c =targetCase.LastmodifiedBy.Name;//印刷連番
        switch on proc_code {
            when '01' {
                print.ProcName__c = 'トップメニュー（自動車・火災）';//処理名
            }
            when '02' {
                print.ProcName__c = 'トップメニュー(傷害）';//処理名
            }
            when '11' {
                print.ProcName__c = '自動車見積書作成【純新規】';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when '12' {
                print.ProcName__c = '自動車見積書作成【新規】';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when '13' {
                print.ProcName__c = '自動車見積書作成【再作成】';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when '14' {
                print.ProcName__c = '自動車見積書作成【更改】';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when '21' {
                print.ProcName__c = '自動車申込書作成';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when '22' {
                print.ProcName__c = '自動車申込書作成【再作成】';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when '23' {
                print.ProcName__c = '自動車申込書作成【試算用】';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when '31' {
                print.ProcName__c = '自動車承認請求書作成';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when '32' {
                print.ProcName__c = '自動車承認請求書再作成';//処理名
                targetCase.ExpectedShippingDate_Latest__c = Date.today().addDays(1);
                targetCase.ReturnFollow_UpDate_Latest__c = Date.today().addDays(8);
                targetCase.NoFollow_UpRequired__c = false;
                targetCase.ShipmentRequired__c = true;
            }
            when else {		  // default block, optional
                print.ProcName__c = 'その他';//処理名
            }
        }
        insert print;
        targetCase.PrintSerialNumber__c = params.ccRnki_InstRnbn;//印刷連番
        update targetCase;
        res.statusCode = 200;
        return;
    }
    public class Request{
        String gyoumu_Id;
        String ccRnki_InstRnbn;
        String ccRnki_SyknNo;
        String ccRnki_SyknNoEdbn;
        String ccRnki_HknSiki;
        String ccRnki_P1_HknSyki;
        String ccRnki_P2_HknSyki;
        String ccRnki_P3_HknSyki;
        String p1_HrikmHuhu;
        String p2_HrikmHuhu;
        String p3_HrikmHuhu;
        String ccRnki_P1_HrikmHuhu;
        String ccRnki_P2_HrikmHuhu;
        String ccRnki_P3_HrikmHuhu;
        String ccRnki_P1_GukiHknr;
        String ccRnki_P2_GukiHknr;
        String ccRnki_P3_GukiHknr;
        String ccRnki_P1_SuGkHknr;
        String ccRnki_P2_SuGkHknr;
        String ccRnki_P3_SuGkHknr;
        String ccRnki_IduD;
        String ccRnki_GukiHknr;
        String pdfFilePath;
        String pdfFiledata;
    }
}