force-app/main/default/objects/Case/fields/CommencementInsuranceWareki__c.field-meta.xml
<CustomField>
    <fullName>CommencementInsuranceWareki__c</fullName>
    <label>保険始期（和暦）（代理店報告リスト用）</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContractInformationId__c.field-meta.xml
<CustomField>
    <fullName>ContractInformationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約情報</label>
    <referenceTo>Contract_Information__c</referenceTo>
    <relationshipLabel>カスタマーセンターコールデータ</relationshipLabel>
    <relationshipName>Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>証券番号</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PrintSerialNumber__c.field-meta.xml
<CustomField>
    <fullName>PrintSerialNumber__c</fullName>
    <label>印刷連番</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/PrintSerialNumber__c.object-meta.xml
<CustomObject>
    <label>印刷連番</label>
    <nameField>
        <label>印刷連番</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrintSerialNumber__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>カスタマーセンターコールデータ</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>印刷連番</relationshipLabel>
    <relationshipName>PrintSerialNumber</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/CommencementInsuranceWareki__c.field-meta.xml
<CustomField>
    <fullName>CommencementInsuranceWareki__c</fullName>
    <label>保険始期（和暦）</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/Contract_InformationId__c.field-meta.xml
<CustomField>
    <fullName>Contract_InformationId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>契約情報</label>
    <referenceTo>Contract_Information__c</referenceTo>
    <relationshipLabel>印刷連番</relationshipLabel>
    <relationshipName>PrintSerialNumber</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodA__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodA__c</fullName>
    <label>(Aプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodB__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodB__c</fullName>
    <label>(Bプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodC__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodC__c</fullName>
    <label>(Cプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodA__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodA__c</fullName>
    <label>新払込方法（Aプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodB__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodB__c</fullName>
    <label>新払込方法（Bプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodC__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodC__c</fullName>
    <label>新払込方法（Cプラン）</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationA__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationA__c</fullName>
    <label>(Aプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationB__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationB__c</fullName>
    <label>(Bプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PaymentMethodTranslationC__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethodTranslationC__c</fullName>
    <label>(Cプラン)払込方法翻訳</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PdfFilePath__c.field-meta.xml
<CustomField>
    <fullName>PdfFilePath__c</fullName>
    <label>PDFファイルパス名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PolicyBranchNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyBranchNumber__c</fullName>
    <label>証券番号枝番</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>証券番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/ProcName__c.field-meta.xml
<CustomField>
    <fullName>ProcName__c</fullName>
    <label>処理名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeA__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeA__c</fullName>
    <label>(Aプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeB__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeB__c</fullName>
    <label>(Bプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeC__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeC__c</fullName>
    <label>(Cプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeA__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeA__c</fullName>
    <label>(Aプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeB__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeB__c</fullName>
    <label>(Bプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/TotalInsuranceFeeC__c.field-meta.xml
<CustomField>
    <fullName>TotalInsuranceFeeC__c</fullName>
    <label>(Cプラン)総額保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/GetOnlinePrintProcController.cls
public without Sharing class GetOnlinePrintProcController{

    public GetOnlinePrintProcController(){
    }
    public void processIncomingData() {
            // Retrieve POST data
            Map<String,String> postData = ApexPages.currentPage().getParameters();
            System.debug('POSTデータ: ' + postData);
            System.debug(ApexPages.currentPage().getParameters());
            
            //If POST data is blank, redirect immediately
            if (postData == null || postData.isEmpty()) {
                return;
            }
            String gyoumu_Id;
            String ccRnki_InstRnbn;
            String ccRnki_SyknNo;
            String ccRnki_SyknNoEdbn;
            String ccRnki_HknSiki;
            String ccRnki_P1_HknSyki;
            String ccRnki_P2_HknSyki;
            String ccRnki_P3_HknSyki;
            String p1_HrikmHuhu;
            String p2_HrikmHuhu;
            String p3_HrikmHuhu;
            String ccRnki_P1_HrikmHuhu;
            String ccRnki_P2_HrikmHuhu;
            String ccRnki_P3_HrikmHuhu;
            String ccRnki_P1_GukiHknr;
            String ccRnki_P2_GukiHknr;
            String ccRnki_P3_GukiHknr;
            String ccRnki_P1_SuGkHknr;
            String ccRnki_P2_SuGkHknr;
            String ccRnki_P3_SuGkHknr;
            String pdfFilePath;
            String pdfFiledata;
            for(String key : postData.keySet()){
                if(key.toLowerCase() == 'gyoumu_Id'.toLowerCase()){
                    gyoumu_Id = postData.get(key);
                }else if(key.toLowerCase() == 'ccRnki_InstRnbn'.toLowerCase()){
                    ccRnki_InstRnbn = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_SyknNo'.toLowerCase()){
                    ccRnki_SyknNo = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_SyknNoEdbn'.toLowerCase()){
                    ccRnki_SyknNoEdbn = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_HknSiki'.toLowerCase()){
                    ccRnki_HknSiki = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P1_HknSyki'.toLowerCase()){
                    ccRnki_P1_HknSyki = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P2_HknSyki'.toLowerCase()){
                    ccRnki_P2_HknSyki = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P3_HknSyki'.toLowerCase()){
                    ccRnki_P3_HknSyki = postData.get(key);

                }else if(key.toLowerCase() == 'p1_HrikmHuhu'.toLowerCase()){
                    p1_HrikmHuhu = postData.get(key);

                }else if(key.toLowerCase() == 'p2_HrikmHuhu'.toLowerCase()){
                    p2_HrikmHuhu = postData.get(key);

                }else if(key.toLowerCase() == 'p3_HrikmHuhu'.toLowerCase()){
                    p3_HrikmHuhu = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P1_HrikmHuhu'.toLowerCase()){
                    ccRnki_P1_HrikmHuhu = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P2_HrikmHuhu'.toLowerCase()){
                    ccRnki_P2_HrikmHuhu = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P3_HrikmHuhu'.toLowerCase()){
                    ccRnki_P3_HrikmHuhu = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P1_GukiHknr'.toLowerCase()){
                    ccRnki_P1_GukiHknr = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P2_GukiHknr'.toLowerCase()){
                    ccRnki_P2_GukiHknr = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P3_GukiHknr'.toLowerCase()){
                    ccRnki_P3_GukiHknr = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P1_SuGkHknr'.toLowerCase()){
                    ccRnki_P1_SuGkHknr = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P2_SuGkHknr'.toLowerCase()){
                    ccRnki_P2_SuGkHknr = postData.get(key);

                }else if(key.toLowerCase() == 'ccRnki_P3_SuGkHknr'.toLowerCase()){
                    ccRnki_P3_SuGkHknr = postData.get(key);

                }else if(key.toLowerCase() == 'pdfFilePath'.toLowerCase()){
                    pdfFilePath = postData.get(key);

                }else if(key.toLowerCase() == 'pdfFiledata'.toLowerCase()){
                    pdfFiledata = postData.get(key);

                }
            }
            if(String.isBlank(gyoumu_id)){
                //エラー
                return;
            }

            if(gyoumu_Id.left(3) <> '500'){
                return;
            }
            Case targetCase = [Select Id, ContractInformationId__c From Case Where Id = :gyoumu_Id limit 1];
            if(targetCase == null){
                return;
            }
            Attachment att= new Attachment();
            att.parentId = targetCase.Id;
            att.Body = EncodingUtil.Base64Decode(pdfFiledata);
            att.Name = pdfFilePath.right(pdfFilePath.length() - pdfFilePath.lastIndexOf('\\') +1);
            insert att;
            PrintSerialNumber__c print = new PrintSerialNumber__c();
            print.CaseId__c = targetCase.Id;//ケースId
            print.Contract_InformationId__c = targetCase.ContractInformationId__c;//契約情報
            print.Name = ccRnki_InstRnbn;//印刷連番
            print.PolicyNumber__c = ccRnki_SyknNo;//証券番号
            print.PolicyBranchNumber__c = ccRnki_SyknNoEdbn;//証券番号枝番
            print.CommencementInsuranceWareki__c = ccRnki_HknSiki;//保険始期
            print.InsurancePeriodA__c = ccRnki_P1_HknSyki;//(Aプラン)保険終期
            print.InsurancePeriodB__c = ccRnki_P2_HknSyki;//(Bプラン)保険終期
            print.InsurancePeriodC__c = ccRnki_P3_HknSyki;//(Cプラン)保険終期
            print.PaymentMethodA__c = p1_HrikmHuhu;//(Aプラン)払込方法
            print.PaymentMethodB__c = p2_HrikmHuhu;//(Bプラン)払込方法
            print.PaymentMethodC__c = p3_HrikmHuhu;//(Cプラン)払込方法
            print.PaymentMethodTranslationA__c = ccRnki_P1_HrikmHuhu;//(Aプラン)払込方法翻訳
            print.PaymentMethodTranslationB__c = ccRnki_P2_HrikmHuhu;//(Bプラン)払込方法翻訳
            print.PaymentMethodTranslationC__c = ccRnki_P3_HrikmHuhu;//(Cプラン)払込方法翻訳
            print.SumInsuranceFeeA__c = String.isBlank(ccRnki_P1_GukiHknr) ? 0 : Decimal.valueOf(ccRnki_P1_GukiHknr);//(Aプラン)合計保険料
            print.SumInsuranceFeeB__c = String.isBlank(ccRnki_P2_GukiHknr) ? 0 : Decimal.valueOf(ccRnki_P2_GukiHknr);//(Bプラン)合計保険料
            print.SumInsuranceFeeC__c = String.isBlank(ccRnki_P3_GukiHknr) ? 0 : Decimal.valueOf(ccRnki_P3_GukiHknr);//(Cプラン)合計保険料
            print.TotalInsuranceFeeA__c = String.isBlank(ccRnki_P1_SuGkHknr) ? 0 : Decimal.valueOf(ccRnki_P1_SuGkHknr);//(Aプラン)総額保険料
            print.TotalInsuranceFeeB__c = String.isBlank(ccRnki_P2_SuGkHknr) ? 0 : Decimal.valueOf(ccRnki_P2_SuGkHknr);//(Bプラン)総額保険料
            print.TotalInsuranceFeeC__c = String.isBlank(ccRnki_P3_SuGkHknr) ? 0 : Decimal.valueOf(ccRnki_P3_SuGkHknr);//(Cプラン)総額保険料
            print.PdfFilePath__c = pdfFilePath;//PDFファイルパス名
            print.ProcName__c = att.Name;//処理名
                
    
    }
}