force-app/main/default/objects/Case/fields/PrintSerialNumber__c.field-meta.xml
<CustomField>
    <fullName>PrintSerialNumber__c</fullName>
    <label>印刷連番</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/PrintSerialNumber__c.object-meta.xml
<CustomObject>
    <label>印刷連番</label>
    <nameField>
        <label>印刷連番</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PrintSerialNumber__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>カスタマーセンターコールデータ</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>印刷連番</relationshipLabel>
    <relationshipName>PrintSerialNumber</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodA__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodA__c</fullName>
    <label>(Aプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodB__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodB__c</fullName>
    <label>(Bプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/InsurancePeriodC__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriodC__c</fullName>
    <label>(Cプラン)保険終期</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeA__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeA__c</fullName>
    <label>(Aプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeB__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeB__c</fullName>
    <label>(Bプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PrintSerialNumber__c/fields/SumInsuranceFeeC__c.field-meta.xml
<CustomField>
    <fullName>SumInsuranceFeeC__c</fullName>
    <label>(Cプラン)合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OnlinePrintProcControllerTests.cls
@isTest
public class OnlinePrintProcControllerTests{

	@isTest
    static void getUserOnlineInfoTest(){
		  List<User> users = OnlinePrintProcController.getUserOnlineInfo();
    }
  @isTest
    static void getPrintDatasTest(){
      Case c = new Case();
      Insert c;

      PrintSerialNumber__c p = new PrintSerialNumber__c();
      p.Name = 'A1111';
      p.CaseId__c = c.Id;
      p.InsurancePeriodA__c = 'R010101';
      p.InsurancePeriodB__c = 'R010102';
      p.InsurancePeriodC__c = 'R010103';
      p.SumInsuranceFeeA__c = 100;
      p.SumInsuranceFeeB__c = 200;
      p.SumInsuranceFeeC__c = 300;
      Insert p;

      List<Map<String, String>>  maps = OnlinePrintProcController.getPrintDatas(c.Id);
    }
}