force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressKana__c.field-meta.xml
<CustomField>
    <fullName>AddressKana__c</fullName>
    <label>住所カナ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>代理店コード</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AgencyName__c.field-meta.xml
<CustomField>
    <fullName>AgencyName__c</fullName>
    <label>代理店名</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CounterpartyCode__c.field-meta.xml
<CustomField>
    <fullName>CounterpartyCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>相手先コード</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FukokuBranchCode__c.field-meta.xml
<CustomField>
    <fullName>FukokuBranchCode__c</fullName>
    <label>富国支社コード</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/JurisdictionalStoreCode__c.field-meta.xml
<CustomField>
    <fullName>JurisdictionalStoreCode__c</fullName>
    <externalId>true</externalId>
    <label>営業店コード</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesBranchName__c.field-meta.xml
<CustomField>
    <fullName>SalesBranchName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>営業店名</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>営業店</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>代理店</relationshipLabel>
    <relationshipName>SalesBranchName_relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Accident__c.field-meta.xml
<CustomField>
    <fullName>Accident__c</fullName>
    <defaultValue>false</defaultValue>
    <label>事故有無</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AddressKana__c.field-meta.xml
<CustomField>
    <fullName>AddressKana__c</fullName>
    <label>住所カナ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>FinServ__Age__c</formula>
    <label>契約者年齢</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>代理店名コード</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AgencyName__c.field-meta.xml
<CustomField>
    <fullName>AgencyName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>代理店名</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>代理店</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>代理店連絡先</relationshipLabel>
    <relationshipName>AgencyName</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <formula>Birthdate</formula>
    <label>契約者生年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CIFCode__c.field-meta.xml
<CustomField>
    <fullName>CIFCode__c</fullName>
    <label>CIFコード</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CollectiveCode__c.field-meta.xml
<CustomField>
    <fullName>CollectiveCode__c</fullName>
    <label>集団コード</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CommencementInsurance__c.field-meta.xml
<CustomField>
    <fullName>CommencementInsurance__c</fullName>
    <label>保険始期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FukokuBranchCode__c.field-meta.xml
<CustomField>
    <fullName>FukokuBranchCode__c</fullName>
    <label>富国支社コード</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>性別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>男</fullName>
            </value>
            <value>
                <fullName>女</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/GroupList__c.field-meta.xml
<CustomField>
    <fullName>GroupList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>集団コード</label>
    <referenceTo>GroupCode__c</referenceTo>
    <relationshipLabel>取引先責任者</relationshipLabel>
    <relationshipName>GroupList_relation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <label>集団名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/InsuranceFee__c.field-meta.xml
<CustomField>
    <fullName>InsuranceFee__c</fullName>
    <label>合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/JurisdictionalStoreCode__c.field-meta.xml
<CustomField>
    <fullName>JurisdictionalStoreCode__c</fullName>
    <label>営業店コード</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LineInsurance__c.field-meta.xml
<CustomField>
    <fullName>LineInsurance__c</fullName>
    <label>保険種目</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailOrderSpecialSales__c.field-meta.xml
<CustomField>
    <fullName>MailOrderSpecialSales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>通販特約有無</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OfficeCode__c.field-meta.xml
<CustomField>
    <fullName>OfficeCode__c</fullName>
    <label>相対支社コード</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyholderName__c.field-meta.xml
<CustomField>
    <fullName>PolicyholderName__c</fullName>
    <label>契約者名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyholderName_Kana__c.field-meta.xml
<CustomField>
    <fullName>PolicyholderName_Kana__c</fullName>
    <label>契約者名カナ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyholderTEL__c.field-meta.xml
<CustomField>
    <fullName>PolicyholderTEL__c</fullName>
    <label>契約者電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SalesBranchName__c.field-meta.xml
<CustomField>
    <fullName>SalesBranchName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>営業店名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>取引先責任者 (担当営業店名)</relationshipLabel>
    <relationshipName>Acc_Con_Eigyou</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SecurityNumberParentNumber__c.field-meta.xml
<CustomField>
    <fullName>SecurityNumberParentNumber__c</fullName>
    <label>証券番号 親番</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TermOfInsurance__c.field-meta.xml
<CustomField>
    <fullName>TermOfInsurance__c</fullName>
    <label>保険終期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/Contract_Information__c.object-meta.xml
<CustomObject>
    <label>契約情報</label>
    <nameField>
        <label>契約情報名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Information__c/fields/AccidentYesNo__c.field-meta.xml
<CustomField>
    <fullName>AccidentYesNo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>事故有無</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/AccountManagement__c.field-meta.xml
<CustomField>
    <fullName>AccountManagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先管理用項目</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>契約情報</relationshipLabel>
    <relationshipName>AccountContract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>契約者住所</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/AddressKana__c.field-meta.xml
<CustomField>
    <fullName>AddressKana__c</fullName>
    <label>住所カナ</label>
    <length>104</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/AgencyCode__c.field-meta.xml
<CustomField>
    <fullName>AgencyCode__c</fullName>
    <label>代理店コード</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>契約者生年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/BranchCode__c.field-meta.xml
<CustomField>
    <fullName>BranchCode__c</fullName>
    <label>相対支社コード</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/CifCode__c.field-meta.xml
<CustomField>
    <fullName>CifCode__c</fullName>
    <label>CIFコード</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/CollectiveCode__c.field-meta.xml
<CustomField>
    <fullName>CollectiveCode__c</fullName>
    <label>集団コード</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/CollectiveName__c.field-meta.xml
<CustomField>
    <fullName>CollectiveName__c</fullName>
    <label>集団名</label>
    <length>52</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/ContractorKana__c.field-meta.xml
<CustomField>
    <fullName>ContractorKana__c</fullName>
    <label>契約者名カナ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/InsuranceFee__c.field-meta.xml
<CustomField>
    <fullName>InsuranceFee__c</fullName>
    <label>合計保険料</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/InsuranceItem__c.field-meta.xml
<CustomField>
    <fullName>InsuranceItem__c</fullName>
    <label>保険種目</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/InsurancePeriod__c.field-meta.xml
<CustomField>
    <fullName>InsurancePeriod__c</fullName>
    <label>保険終期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/JurisdictionalStoreCode__c.field-meta.xml
<CustomField>
    <fullName>JurisdictionalStoreCode__c</fullName>
    <label>営業店コード</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/OrganizationCode__c.field-meta.xml
<CustomField>
    <fullName>OrganizationCode__c</fullName>
    <label>富国生命 組織コード</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>契約者電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/R_Contact__c.field-meta.xml
<CustomField>
    <fullName>R_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先責任者名</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>契約情報</relationshipLabel>
    <relationshipName>R_Contact_ContractInformation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/SecuritiesNumber__c.field-meta.xml
<CustomField>
    <fullName>SecuritiesNumber__c</fullName>
    <label>証券番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Information__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>契約者郵便番号</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GroupCode__c/GroupCode__c.object-meta.xml
<CustomObject>
    <label>集団コード</label>
    <nameField>
        <label>集団コード</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GroupCode__c/fields/GroupCode__c.field-meta.xml
<CustomField>
    <fullName>GroupCode__c</fullName>
    <label>集団名</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAccountInfoController.cls
public without Sharing class GetAccountInfoController{

    public GetAccountInfoController(){
    }
    public void processIncomingData() {
            // Retrieve POST data
            Map<String,String> postData = ApexPages.currentPage().getParameters();
            System.debug('POSTデータ: ' + postData);
            System.debug(ApexPages.currentPage().getParameters());
            
            //If POST data is blank, redirect immediately
            if (postData == null || postData.isEmpty()) {
                return;
            }
            String gCode;
            String gyoumu_Id;
            String shoken_No;
            String hkn_Shiki;
            String hkn_Shuki;
            String keiyakusha_Knj;
            String keiyakusha_Kana;
            String keiyakusha_Tel;
            String keiyakusha_Yubin_No;
            String keiyakusha_Jusho_Knj;
            String dairiten_Cd;
            String shokanten_Cd;
            String tsuhan_Umu;
            String shudan_Cd;
            String shudan_Name;
            String jiko_Umu;
            String soshiki_Cd;
            String hkn_Shurui;
            String gokei_HknRyo;
            String keiyakusha_Birth;
            String keiyakusha_Nenrei;
            String keiyakusha_Seibetsu;
            String shisha_Cd;
            String cif_Cd;
            String renrakusaki;
            String haraikomi;
            String keiyakusha_Jusho_Kana;
            for(String key : postData.keySet()){
                if(key.toLowerCase() == 'gCode'.toLowerCase()){
                    gCode = postData.get(key);
                }else if(key.toLowerCase() == 'gyoumu_Id'.toLowerCase()){
                    gyoumu_Id = postData.get(key);

                }else if(key.toLowerCase() == 'shoken_No'.toLowerCase()){
                    shoken_No = postData.get(key);

                }else if(key.toLowerCase() == 'hkn_Shiki'.toLowerCase()){
                    hkn_Shiki = postData.get(key);

                }else if(key.toLowerCase() == 'hkn_Shuki'.toLowerCase()){
                    hkn_Shuki = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Knj'.toLowerCase()){
                    keiyakusha_Knj = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Kana'.toLowerCase()){
                    keiyakusha_Kana = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Tel'.toLowerCase()){
                    keiyakusha_Tel = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Yubin_No'.toLowerCase()){
                    keiyakusha_Yubin_No = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Jusho_Knj'.toLowerCase()){
                    keiyakusha_Jusho_Knj = postData.get(key);

                }else if(key.toLowerCase() == 'dairiten_Cd'.toLowerCase()){
                    dairiten_Cd = postData.get(key);

                }else if(key.toLowerCase() == 'shokanten_Cd'.toLowerCase()){
                    shokanten_Cd = postData.get(key);

                }else if(key.toLowerCase() == 'tsuhan_Umu'.toLowerCase()){
                    tsuhan_Umu = postData.get(key);

                }else if(key.toLowerCase() == 'shudan_Cd'.toLowerCase()){
                    shudan_Cd = postData.get(key);

                }else if(key.toLowerCase() == 'shudan_Name'.toLowerCase()){
                    shudan_Name = postData.get(key);

                }else if(key.toLowerCase() == 'jiko_Umu'.toLowerCase()){
                    jiko_Umu = postData.get(key);

                }else if(key.toLowerCase() == 'soshiki_Cd'.toLowerCase()){
                    soshiki_Cd = postData.get(key);

                }else if(key.toLowerCase() == 'hkn_Shurui'.toLowerCase()){
                    hkn_Shurui = postData.get(key);

                }else if(key.toLowerCase() == 'gokei_HknRyo'.toLowerCase()){
                    gokei_HknRyo = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Birth'.toLowerCase()){
                    keiyakusha_Birth = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Nenrei'.toLowerCase()){
                    keiyakusha_Nenrei = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Seibetsu'.toLowerCase()){
                    keiyakusha_Seibetsu = postData.get(key);

                }else if(key.toLowerCase() == 'shisha_Cd'.toLowerCase()){
                    shisha_Cd = postData.get(key);

                }else if(key.toLowerCase() == 'cif_Cd'.toLowerCase()){
                    cif_Cd = postData.get(key);

                }else if(key.toLowerCase() == 'renrakusaki'.toLowerCase()){
                    renrakusaki = postData.get(key);

                }else if(key.toLowerCase() == 'haraikomi'.toLowerCase()){
                    haraikomi = postData.get(key);

                }else if(key.toLowerCase() == 'keiyakusha_Jusho_Kana'.toLowerCase()){
                    keiyakusha_Jusho_Kana = postData.get(key);
                }
            }
            if(String.isBlank(gyoumu_id)){
                //エラー
                return;
            }
            Contract_Information__c contract = new Contract_Information__c();

            if(gyoumu_Id.left(3) == '003'){
                //Contact
                Contact c = new Contact(Id = gyoumu_Id);
                c.SecurityNumberParentNumber__c = shoken_No;//証券番号
                if(String.isNotBlank(hkn_Shiki)){
                    c.CommencementInsurance__c = 
                        Date.newInstance(Integer.valueOf(hkn_Shiki.left(4)),Integer.valueOf(hkn_Shiki.mid(4, 2)),Integer.valueOf(hkn_Shiki.right(2)));//保険始期
                }else{
                    c.CommencementInsurance__c = null;
                }
                
                if(String.isNotBlank(hkn_Shuki)){
                    c.TermOfInsurance__c = 
                        Date.newInstance(Integer.valueOf(hkn_Shuki.left(4)),Integer.valueOf(hkn_Shuki.mid(4, 2)),Integer.valueOf(hkn_Shuki.right(2)));//保険終期
                }else{
                    c.TermOfInsurance__c = null;
                }
                c.PolicyholderName__c = keiyakusha_Knj;//契約者名
                c.PolicyholderName_Kana__c = keiyakusha_Kana;//契約者名カナ
                c.PolicyholderTEL__c = keiyakusha_Tel;//契約者電話番号
                c.PostalCode__c = keiyakusha_Yubin_No.replaceAll('-', '');//郵便番号
                c.Address__c = keiyakusha_Jusho_Knj;//契約者住所
                c.AgencyCode__c = dairiten_Cd;//代理店コード
                List<Account> dairitens = [select id from Account Where CounterpartyCode__c = :dairiten_Cd];
                if(!dairitens.isEmpty()) c.AgencyName__c =dairitens.get(0).Id;
                c.JurisdictionalStoreCode__c = shokanten_Cd;//所管店コード

                List<Account> eigyotens = [select id from Account Where CounterpartyCode__c = :shokanten_Cd];
                if(!eigyotens.isEmpty()) c.SalesBranchName__c =eigyotens.get(0).Id;

                c.MailOrderSpecialSales__c = String.isBlank(tsuhan_Umu)? false : true;  //通販特約有無
                c.CollectiveCode__c = shudan_Cd;//集団コード
                
                List<GroupCode__c> groupCodes = [select id from GroupCode__c Where Name = :shudan_Cd];
                if(!groupCodes.isEmpty()) c.GroupList__c =groupCodes.get(0).Id;
                c.GroupName__c = shudan_Name;//集団名
                c.Accident__c = String.isBlank(jiko_Umu)? false : true;//事故有無
                c.FukokuBranchCode__c = soshiki_Cd;//富国生命 組織コード
                c.LineInsurance__c = hkn_Shurui;//保険種目
                // = shoken_No;合計保険料
                
                if(String.isNotBlank(keiyakusha_Birth)){
                    //c.Birthdate =
                    //    Date.newInstance(Integer.valueOf(keiyakusha_Birth.left(4)),Integer.valueOf(keiyakusha_Birth.mid(4, 2)),Integer.valueOf(keiyakusha_Birth.right(2)));//契約者生年月日
                }else{
                    //c.Birthdate = null;
                }
                // = shoken_No;契約者年齢
                c.Gender__c = keiyakusha_Seibetsu;//契約者性別
                c.OfficeCode__c = shisha_Cd;//相対支社コード
                c.CIFCode__c = cif_Cd;//CIFコード
                //c. = renrakusaki;//事務上連絡先
                //c. = haraikomi;//払込方法
                c.AddressKana__c = keiyakusha_Jusho_Kana;//住所カナ
                update c;

                contract.R_Contact__c = c.Id;
                contract.AccountManagement__c = c.AgencyName__c;
            }
            contract.Name = shoken_No;
            contract.SecuritiesNumber__c = shoken_No; //証券番号
            if(String.isNotBlank(hkn_Shiki)){
                contract.InsuranceFrom__c = 
                    Date.newInstance(Integer.valueOf(hkn_Shiki.left(4)),Integer.valueOf(hkn_Shiki.mid(4, 2)),Integer.valueOf(hkn_Shiki.right(2)));//保険始期
            }else{
                contract.InsuranceFrom__c = null;
            }
            if(String.isNotBlank(hkn_Shuki)){
                contract.InsurancePeriod__c =
                Date.newInstance(Integer.valueOf(hkn_Shuki.left(4)),Integer.valueOf(hkn_Shuki.mid(4, 2)),Integer.valueOf(hkn_Shuki.right(2)));//保険終期
            }else{
                contract.InsurancePeriod__c = null;
            }
            
            contract.ContractorName__c = keiyakusha_Knj; //契約者名
            contract.ContractorKana__c = keiyakusha_Kana; //契約者名カナ
            contract.PhoneNumber__c = keiyakusha_Tel; //契約者電話番号
            contract.ZipCode__c = keiyakusha_Yubin_No; //契約者郵便番号
            contract.Address__c = keiyakusha_Jusho_Knj; //契約者住所
            contract.AgencyCode__c = dairiten_Cd; //代理店コード
            contract.JurisdictionalStoreCode__c = shokanten_Cd; //所管店コード
            contract.SpecialAgreementYesNo__c = String.isBlank(tsuhan_Umu)? false : true;  //通販特約有無
            contract.CollectiveCode__c = shudan_Cd; //集団コード
            contract.CollectiveName__c = shudan_Name; //集団名
            contract.AccidentYesNo__c = String.isBlank(jiko_Umu)? false : true;//事故有無
            contract.OrganizationCode__c = soshiki_Cd; //富国生命 組織コード
            contract.InsuranceItem__c = hkn_Shurui; //保険種目
            contract.InsuranceFee__c = Integer.valueOf(gokei_HknRyo); //合計保険料
            
            if(String.isNotBlank(keiyakusha_Birth)){
                contract.Birthday__c = 
                    Date.newInstance(Integer.valueOf(keiyakusha_Birth.left(4)),Integer.valueOf(keiyakusha_Birth.mid(4, 2)),Integer.valueOf(keiyakusha_Birth.right(2)));//契約者生年月日
            
            }else{
                contract.Birthday__c = null;
            }
            contract.Age__c = Integer.valueOf(keiyakusha_Nenrei); //契約者年齢
            contract.Sex__c = keiyakusha_Seibetsu; //契約者性別
            contract.BranchCode__c = shisha_Cd; //相対支社コード
            contract.CifCode__c = cif_Cd; //CIFコード
            contract.ContactInfo__c = renrakusaki; //事務上連絡先
            contract.PaymentMethod__c = haraikomi; //払込方法
            contract.AddressKana__c = keiyakusha_Jusho_Kana; //住所カナ
            List<Contract_Information__c> contracts = [Select Id from Contract_Information__c Where Name =:shoken_No];
            if(contracts.isEmpty()){
                insert contract;
            }else{
                contract.Id = contracts.get(0).Id;
                update contract;
            }

    }
}