force-app/main/default/objects/Account/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>備考</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <label>代理店</label>
</RecordType>

force-app/main/default/objects/Case/fields/InquiryDetails__c.field-meta.xml
<CustomField>
    <fullName>InquiryDetails__c</fullName>
    <label>問い合わせ詳細（対応依頼用）</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/PolicyIdentificationMethod__c.field-meta.xml
<CustomField>
    <fullName>PolicyIdentificationMethod__c</fullName>
    <label>契約特定方法</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>証券番号</fullName>
            </value>
            <value>
                <fullName>４項目聴取</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceAccount__c.field-meta.xml
<CustomField>
    <fullName>ReferenceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>代理店名</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>代理店</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>郵便局</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>カスタマーセンターコールデータ_代理店</relationshipLabel>
    <relationshipName>R_Account_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>対応依頼票転記内容</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Auto_ContinuationStop.recordType-meta.xml
<RecordType>
    <fullName>Auto_ContinuationStop</fullName>
    <active>true</active>
    <businessProcess>自継停止</businessProcess>
    <label>自動継続停止</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Fire.recordType-meta.xml
<RecordType>
    <fullName>Fire</fullName>
    <active>true</active>
    <businessProcess>火新異動</businessProcess>
    <label>火新異動</label>
</RecordType>

force-app/main/default/classes/GetAccountInfoRestTests.cls
@isTest
public class GetAccountInfoRestTests{

    private static testMethod void processIncomingDataTest1(){ 
        Case testCase = new Case();
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        Insert testCase;
        Test.startTest(); 
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "1234567890",';
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",';
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "種類テキスト",';
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    private static testMethod void processIncomingDataTest2(){ 
        Account testAccount = new Account();
        RecordType personType = [Select Id From RecordType Where SObjectType = 'Account' And Name = '顧客'].get(0);
        testAccount.LastName = 'テストAccount';
        testAccount.RecordTypeId = personType.Id;
        String tel = '123412341234';
        testAccount.PhoneNumber__c = tel;
        testAccount.PhoneNumber__pc = tel;
        Insert testAccount;
        Test.startTest(); 
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testAccount.Id +'",';
        JSONMsg +='"shoken_No" : "1234567890",';
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",';
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "種類テキスト",';
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //レコードタイプ：火新異動
    private static testMethod void processIncomingDataTest_Fire(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Fire').getRecordTypeId(); //火新異動
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "1234567890",';
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",';
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "個人用火災総合保険",'; //保険種目２（火新異動）
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //JAシニア／安心倶楽部*（標準傷害保険）
    private static testMethod void processIncomingDataTest_Hyojun_JASenior(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "12345678901234567",'; //17桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "8630001",'; //頭3桁863
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "標準傷害保険",'; //標準傷害保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //窓販シニア*（標準傷害保険）
    private static testMethod void processIncomingDataTest_Hyojun_MadohanSenior(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "12345678901234567",'; //17桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "8620001",'; //頭3桁862
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "標準傷害保険",'; //標準傷害保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //しんきんシニア*（標準傷害保険）
    private static testMethod void processIncomingDataTest_Hyojun_ShinkinSenior(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "12345678901234567",'; //17桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "8640001",'; //頭3桁864
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "標準傷害保険",'; //標準傷害保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //窓販シニア*
    private static testMethod void processIncomingDataTest_MadohanSenior(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "12345678901234567",'; //17桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",';
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "普通傷害保険",'; //普通傷害保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //しんきんシニア*
    private static testMethod void processIncomingDataTest_ShinkinSenior(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "12345678901234567",'; //17桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",';
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "安心生活総合（普傷）",'; //安心生活総合（普傷）を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //まごネット*
    private static testMethod void processIncomingDataTest_Magonet(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "12345678901234567",'; //17桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",';
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "こども総合保険",'; //こども総合保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //JA自転車倶楽部*
    private static testMethod void processIncomingDataTest_JAJitensya(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "12345678901234567",'; //17桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",';
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "交通事故傷害保険",'; //交通事故傷害保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //しんきんフルタイム24*
    private static testMethod void processIncomingDataTest_ShinkinFulltime(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "1234567890",'; //10桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",';
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "普通傷害保険",'; //普通傷害保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //しんくみ標準傷害*
    private static testMethod void processIncomingDataTest_ShinkumiHyojunShogai(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "1234567890",'; //10桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "7701000",'; //7701000を設定
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "標準傷害保険",'; //標準傷害保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }

    //しんきん標準傷害*
    private static testMethod void processIncomingDataTest_ShinkinHyojunShogai(){
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        Case testCase = new Case();
        testCase.ReferenceAccount__c = a1.Id;
        testCase.contactId = con1.Id;
        testCase.PolicyIdentificationMethod__c = '証券番号';
        testCase.InquiryDetails__c = 'テスト問い合わせ詳細';
        testCase.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        testCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Auto_ContinuationStop').getRecordTypeId(); //自動継続停止
        Insert testCase;
        
        Test.startTest(); 
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetAccountInfo';
        String JSONMsg = '{';
        JSONMsg +='"gCode" : "xxxxx",';
        JSONMsg +='"gyoumu_Id" : "'+testCase.Id +'",';
        JSONMsg +='"shoken_No" : "1234567890",'; //10桁
        JSONMsg +='"hkn_Shiki" : "20111201",';
        JSONMsg +='"hkn_Shuki" : "20211201",';
        JSONMsg +='"keiyakusha_Knj"  : "契約者",';
        JSONMsg +='"keiyakusha_Kana" : "ケイヤクシャ",';
        JSONMsg +='"keiyakusha_Tel" : "111122223333",';
        JSONMsg +='"keiyakusha_Yubin_No" : "123-4567",';
        JSONMsg +='"keiyakusha_Jusho_Knj" : "住所１２３４５",';
        JSONMsg +='"dairiten_Cd"  : "12345678901",';
        JSONMsg +='"shokanten_Cd" : "12-456",';
        JSONMsg +='"tsuhan_Umu"  : " ",';
        JSONMsg +='"shudan_Cd" : "1234567",'; //7701000以外を設定
        JSONMsg +='"shudan_Name" : "集団名",';
        JSONMsg +='"jiko_Umu" : " ",';
        JSONMsg +='"soshiki_Cd" : "123456",';
        JSONMsg +='"hkn_Shurui" : "標準傷害保険",'; //標準傷害保険を設定
        JSONMsg +='"gokei_HknRyo" : "00000123456",';
        JSONMsg +='"keiyakusha_Birth" : "20010301",';
        JSONMsg +='"keiyakusha_Nenrei" : "20",';
        JSONMsg +='"keiyakusha_Seibetsu" : "女",';
        JSONMsg +='"shisha_Cd" : "123456",';
        JSONMsg +='"cif_Cd" : "123456789012345",';
        JSONMsg +='"renrakusaki" : "111122223333",';
        JSONMsg +='"haraikomi" : "払い込み方法",';
        JSONMsg +='"keiyakusha_Jusho_Kana" : "ジュウショカナ"}';
        req.requestBody = Blob.valueof(JSONMsg);
        req.httpMethod = 'POST';

        RestContext.request = req;
        RestContext.response= res;
        GetAccountInfoRest.processIncomingData();

        Test.stopTest();
    }
}