force-app/main/default/objects/Account/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <label>代理店</label>
</RecordType>

force-app/main/default/objects/DairitenSaport_CallData__c/DairitenSaport_CallData__c.object-meta.xml
<CustomObject>
    <label>代理店サポートコールデータ</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>コール連番</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DairitenSaport_CallData__c/fields/AgencyReference__c.field-meta.xml
<CustomField>
    <fullName>AgencyReference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>相手先名</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notContain</operation>
            <value>顧客</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>代理店サポートコールデータ</relationshipLabel>
    <relationshipName>AgencyAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DairitenSaport_CallData__c/fields/AnswerDetails__c.field-meta.xml
<CustomField>
    <fullName>AnswerDetails__c</fullName>
    <label>回答詳細</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DairitenSaport_CallData__c/fields/Category1__c.field-meta.xml
<CustomField>
    <fullName>Category1__c</fullName>
    <label>カテゴリ①</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0010ＷＥＢオンライン</fullName>
            </value>
            <value>
                <fullName>0020ポータルサイトメニュー</fullName>
            </value>
            <value>
                <fullName>0030業務メニュー</fullName>
            </value>
            <value>
                <fullName>0040ｅ－ＪｉＢＡｉ</fullName>
            </value>
            <value>
                <fullName>0050導入時作業</fullName>
            </value>
            <value>
                <fullName>0060みつもり一家</fullName>
            </value>
            <value>
                <fullName>0070保険会社メニュー</fullName>
            </value>
            <value>
                <fullName>0080生保</fullName>
            </value>
            <value>
                <fullName>0090統合メニュー</fullName>
            </value>
            <value>
                <fullName>0100ＴｏＤｏ・お知らせ</fullName>
            </value>
            <value>
                <fullName>0110共同ＧＷ</fullName>
            </value>
            <value>
                <fullName>0120ハード他</fullName>
            </value>
            <value>
                <fullName>0130ソフトウエア</fullName>
            </value>
            <value>
                <fullName>0140集団扱集金管理</fullName>
            </value>
            <value>
                <fullName>0150他オフラインソフト</fullName>
            </value>
            <value>
                <fullName>0160データ提供</fullName>
            </value>
            <value>
                <fullName>0170タブレット</fullName>
            </value>
            <value>
                <fullName>0800アシストライン照会内容確認（支援事務）</fullName>
            </value>
            <value>
                <fullName>0900他部署を案内・転送</fullName>
            </value>
            <value>
                <fullName>（未設定）</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DairitenSaport_CallData__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>カテゴリ②</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0010申込書</fullName>
            </value>
            <value>
                <fullName>0020承認書</fullName>
            </value>
            <value>
                <fullName>0040代理店計上</fullName>
            </value>
            <value>
                <fullName>0050計上連絡票</fullName>
            </value>
            <value>
                <fullName>0060直接精算</fullName>
            </value>
            <value>
                <fullName>0070異動試算</fullName>
            </value>
            <value>
                <fullName>0080契約照会</fullName>
            </value>
            <value>
                <fullName>0090事故照会</fullName>
            </value>
            <value>
                <fullName>0100保険料試算</fullName>
            </value>
            <value>
                <fullName>0120入金状況照会</fullName>
            </value>
            <value>
                <fullName>0130代理店実績・成績照会</fullName>
            </value>
            <value>
                <fullName>0140代理店登録状況</fullName>
            </value>
            <value>
                <fullName>0150固定帳票</fullName>
            </value>
            <value>
                <fullName>0160印刷連番照会</fullName>
            </value>
            <value>
                <fullName>0170ＷＥＢオンラインその他</fullName>
            </value>
            <value>
                <fullName>0180継続管理</fullName>
            </value>
            <value>
                <fullName>0190団体加入者照会</fullName>
            </value>
            <value>
                <fullName>0200業務適正照会</fullName>
            </value>
            <value>
                <fullName>0210募集人管理</fullName>
            </value>
            <value>
                <fullName>0220未入金管理</fullName>
            </value>
            <value>
                <fullName>0230練習モード</fullName>
            </value>
            <value>
                <fullName>0240募集人事前設定</fullName>
            </value>
            <value>
                <fullName>0250事故進捗状況照会</fullName>
            </value>
            <value>
                <fullName>0260 クレカ払（登録方式）業務</fullName>
            </value>
            <value>
                <fullName>0270振替不能契約</fullName>
            </value>
            <value>
                <fullName>0280レジペイ</fullName>
            </value>
            <value>
                <fullName>0290他社証券等読取り</fullName>
            </value>
            <value>
                <fullName>0300オンライン領収証</fullName>
            </value>
            <value>
                <fullName>0310ネット口振</fullName>
            </value>
            <value>
                <fullName>0320返還指図書</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DairitenSaport_CallData__c/fields/InquiryDetails__c.field-meta.xml
<CustomField>
    <fullName>InquiryDetails__c</fullName>
    <label>問い合わせ詳細</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DairitenSaport_CallData__c/recordTypes/Automobile.recordType-meta.xml
<RecordType>
    <fullName>Automobile</fullName>
    <active>true</active>
    <label>A.アシストライン（自動車）</label>
</RecordType>

force-app/main/default/classes/AgencyMailCompControllerTest.cls
@isTest
public class AgencyMailCompControllerTest {

    //テストデータ
    @testSetup
    private static void createTestDatas() {
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;
    }

    private static testMethod void SearchTest_ContractorAddress() {
        //代理店コールデータ
        DairitenSaport_CallData__c da1 = new DairitenSaport_CallData__c();
        da1.AgencyReference__c = [SELECT Name FROM Account LIMIT 1].Id;
        da1.Category1__c = '0010ＷＥＢオンライン';
        da1.Category2__c = '0010申込書';
        da1.InquiryDetails__c = 'テスト問い合わせ詳細あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        da1.AnswerDetails__c = 'テスト回答詳細あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        da1.RecordTypeId = Schema.SObjectType.DairitenSaport_CallData__c.getRecordTypeInfosByDeveloperName().get('Automobile').getRecordTypeId();
        insert da1;

        AgencyMailCompController ctrl = new AgencyMailCompController() ;
        ctrl.agencyId = da1.Id;
    }
}