force-app/main/default/objects/Account/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <label>代理店</label>
</RecordType>

force-app/main/default/objects/AddressMaster__c/AddressMaster__c.object-meta.xml
<CustomObject>
    <label>住所マスタ</label>
    <nameField>
        <label>住所マスタ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressMaster__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>漢字市区群名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressMaster__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressMaster__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>漢字都道府県名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressMaster__c/fields/Town__c.field-meta.xml
<CustomField>
    <fullName>Town__c</fullName>
    <label>漢字町村以下名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressMaster__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <externalId>true</externalId>
    <label>ユニークキー</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/CancellationCompletion_Address__c.field-meta.xml
<CustomField>
    <fullName>CancellationCompletion_Address__c</fullName>
    <label>解約完了_送付先住所</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ChangeOfAddress__c.field-meta.xml
<CustomField>
    <fullName>ChangeOfAddress__c</fullName>
    <label>被保険者住所変更有無</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>無し</fullName>
            </value>
            <value>
                <fullName>有</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ChangeOfSubscriberInformation__c.field-meta.xml
<CustomField>
    <fullName>ChangeOfSubscriberInformation__c</fullName>
    <label>契約者情報変更の有無</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>無し</fullName>
            </value>
            <value>
                <fullName>有</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ContractorAddress__c.field-meta.xml
<CustomField>
    <fullName>ContractorAddress__c</fullName>
    <label>契約者住所</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/counterparty_Kana__c.field-meta.xml
<CustomField>
    <fullName>counterparty_Kana__c</fullName>
    <label>入電者カナ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateOfTransfer__c.field-meta.xml
<CustomField>
    <fullName>DateOfTransfer__c</fullName>
    <label>異動日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Incomplete_Address__c.field-meta.xml
<CustomField>
    <fullName>Incomplete_Address__c</fullName>
    <label>書類不備_送付先住所</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Insured_AddressAfterChange1__c.field-meta.xml
<CustomField>
    <fullName>Insured_AddressAfterChange1__c</fullName>
    <label>（新）被保険者住所</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/MailingAddress__c.field-meta.xml
<CustomField>
    <fullName>MailingAddress__c</fullName>
    <label>送付先住所</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/MovedOut__c.field-meta.xml
<CustomField>
    <fullName>MovedOut__c</fullName>
    <label>転居済</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>転居済</fullName>
            </value>
            <value>
                <fullName>転居前</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Post_ChangeSubscriber_AddressKana__c.field-meta.xml
<CustomField>
    <fullName>Post_ChangeSubscriber_AddressKana__c</fullName>
    <label>（新）契約者住所カナ</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Post_ChangeSubscriber_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>Post_ChangeSubscriber_ZipCode__c</fullName>
    <label>（新）契約者郵便番号</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>送付先郵便番号</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReceiptItem_Reason_Multi__c.field-meta.xml
<CustomField>
    <fullName>ReceiptItem_Reason_Multi__c</fullName>
    <description>2024.03.28　受付項目（事由）複数選択リスト</description>
    <label>受付項目（事由）_複数</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>解約</fullName>
            </value>
            <value>
                <fullName>解約（中途解約）</fullName>
            </value>
            <value>
                <fullName>車両入替</fullName>
            </value>
            <value>
                <fullName>契約者住所変更</fullName>
            </value>
            <value>
                <fullName>電話番号変更</fullName>
            </value>
            <value>
                <fullName>被保険者住所変更</fullName>
            </value>
            <value>
                <fullName>その他変更</fullName>
            </value>
            <value>
                <fullName>自動継続停止</fullName>
            </value>
            <value>
                <fullName>死亡解約</fullName>
            </value>
            <value>
                <fullName>書類送付</fullName>
            </value>
            <value>
                <fullName>契約者名変更（改姓）</fullName>
            </value>
            <value>
                <fullName>名義変更（契約者）</fullName>
            </value>
            <value>
                <fullName>名義変更（記名被保険者）</fullName>
            </value>
            <value>
                <fullName>名義変更（車両所有者）</fullName>
            </value>
            <value>
                <fullName>運転者限定・年齢条件変更</fullName>
            </value>
            <value>
                <fullName>その他補償内容・特約変更</fullName>
            </value>
            <value>
                <fullName>記名被保険者住所変更</fullName>
            </value>
            <value>
                <fullName>増車</fullName>
            </value>
            <value>
                <fullName>解約（任意）</fullName>
            </value>
            <value>
                <fullName>解約（中途更改）</fullName>
            </value>
            <value>
                <fullName>証券再発行</fullName>
            </value>
            <value>
                <fullName>照会</fullName>
            </value>
            <value>
                <fullName>照会（計上G）</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>その他異動</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceAccount__c.field-meta.xml
<CustomField>
    <fullName>ReferenceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>代理店名</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>代理店</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>郵便局</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>カスタマーセンターコールデータ_代理店</relationshipLabel>
    <relationshipName>R_Account_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SubscribersAddressAfterChange1__c.field-meta.xml
<CustomField>
    <fullName>SubscribersAddressAfterChange1__c</fullName>
    <label>（新）契約者住所</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/AutomobileMaturity.recordType-meta.xml
<RecordType>
    <fullName>AutomobileMaturity</fullName>
    <active>true</active>
    <businessProcess>自動車満期</businessProcess>
    <label>自動車満期</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/AutomobileTransfers.recordType-meta.xml
<RecordType>
    <fullName>AutomobileTransfers</fullName>
    <active>true</active>
    <businessProcess>自動車異動</businessProcess>
    <label>自動車異動</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/AutomotiveNew.recordType-meta.xml
<RecordType>
    <fullName>AutomotiveNew</fullName>
    <active>true</active>
    <businessProcess>自動車新規</businessProcess>
    <label>自動車新規</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Fire.recordType-meta.xml
<RecordType>
    <fullName>Fire</fullName>
    <active>true</active>
    <businessProcess>火新異動</businessProcess>
    <label>火新異動</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/IndemnityTermination.recordType-meta.xml
<RecordType>
    <fullName>IndemnityTermination</fullName>
    <active>true</active>
    <businessProcess>自賠責解約</businessProcess>
    <label>自賠責解約</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/TransferOfWealth.recordType-meta.xml
<RecordType>
    <fullName>TransferOfWealth</fullName>
    <active>true</active>
    <businessProcess>富国異動</businessProcess>
    <label>富国異動</label>
</RecordType>

force-app/main/default/objects/Contact/fields/ContractorAddress__c.field-meta.xml
<CustomField>
    <fullName>ContractorAddress__c</fullName>
    <label>契約者住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressSearchControllerTest.cls
@isTest
public class AddressSearchControllerTest {
    //テストデータ
    @testSetup
    private static void createTestDatas() {
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        //住所マスタ
        List<AddressMaster__c> addressMasters = new List<AddressMaster__c>();
        
        AddressMaster__c address1 = new AddressMaster__c();
        address1.PostalCode__c = '1500011';
        address1.State__c = '東京都';
        address1.City__c = '渋谷区';
        address1.Town__c = '東１丁目';
        address1.UniqueKey__c = '1500011東京都渋谷区東１丁目';
        addressMasters.add(address1);

        insert addressMasters;
    }

    //自動車新規　契約者住所
    private static testMethod void SearchTest_ContractorAddress() {

        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ１';
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('AutomotiveNew').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ１'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //戻るボタン
        PageReference pageRefGoback = ctrl.goBack();

        //対象項目の選択
        ctrl.TargetField = 'ContractorAddress__c'; //契約者住所
        //次へボタン
        ctrl.goInsert();
        //戻るボタン
        ctrl.goBackSelect();
        //次へボタン
        ctrl.goInsert();

        //郵便番号未入力
        ctrl.PostCode = '';
        ctrl.goSearch();

        //郵便番号該当なし
        ctrl.PostCode = '1600024';
        ctrl.goSearch();

        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        ctrl.goSearch();

        //戻るボタン
        ctrl.goBackInsert();

        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }

    //火新異動　（新）契約者住所
    private static testMethod void SearchTest_SubscribersAddressAfterChange1() {
        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ２';
        ca1.ReceiptItem_Reason_Multi__c = '契約者住所変更'; //受付項目（事由）_複数
        ca1.DateOfTransfer__c = system.today(); //異動日
        ca1.ChangeOfAddress__c = '無し'; //被保険者住所変更有無
        ca1.MovedOut__c = '転居済'; //転居済
        ca1.Post_ChangeSubscriber_ZipCode__c = '1600023'; //（新）契約者郵便番号
        ca1.SubscribersAddressAfterChange1__c = '東京都新宿区'; //（新）契約者住所
        ca1.Post_ChangeSubscriber_AddressKana__c = 'ｼﾞｭｳｼｮｶﾅ'; //（新）契約者住所カナ
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Fire').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ２'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //対象項目の選択
        ctrl.TargetField = 'SubscribersAddressAfterChange1__c'; //（新）契約者住所
        //次へボタン
        ctrl.goInsert();
        
        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }

    //火新異動　（新）被保険者住所
    private static testMethod void SearchTest_Insured_AddressAfterChange1() {
        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ３';
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Fire').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ３'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //対象項目の選択
        ctrl.TargetField = 'Insured_AddressAfterChange1__c'; //（新）被保険者住所
        //次へボタン
        ctrl.goInsert();
        
        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }

    //自賠責解約　送付先住所
    private static testMethod void SearchTest_MailingAddress() {
        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ４';
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('IndemnityTermination').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ４'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //対象項目の選択
        ctrl.TargetField = 'MailingAddress__c'; //送付先住所
        //次へボタン
        ctrl.goInsert();
        
        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }

    //自賠責解約　書類不備_送付先住所
    private static testMethod void SearchTest_Incomplete_Address() {
        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ５';
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('IndemnityTermination').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ５'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //対象項目の選択
        ctrl.TargetField = 'Incomplete_Address__c'; //書類不備_送付先住所
        //次へボタン
        ctrl.goInsert();
        
        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }

    //自賠責解約　解約完了_送付先住所
    private static testMethod void SearchTest_CancellationCompletion_Address() {
        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ６';
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('IndemnityTermination').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ６'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //対象項目の選択
        ctrl.TargetField = 'CancellationCompletion_Address__c'; //解約完了_送付先住所
        //次へボタン
        ctrl.goInsert();
        
        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }

    //富国異動　（新）契約者住所
    private static testMethod void SearchTest_TransferOfWealth() {
        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ７';
        ca1.ChangeOfSubscriberInformation__c ='有'; //契約者情報変更の有無
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TransferOfWealth').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ７'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //対象項目の選択
        ctrl.TargetField = 'SubscribersAddressAfterChange1__c'; //（新）契約者住所
        //次へボタン
        ctrl.goInsert();
        
        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }

    //自動車満期　（新）契約者住所
    private static testMethod void SearchTest_AutomobileMaturity() {
        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ８';
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('AutomobileMaturity').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ８'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //対象項目の選択
        ctrl.TargetField = 'SubscribersAddressAfterChange1__c'; //（新）契約者住所
        //次へボタン
        ctrl.goInsert();
        
        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }

    //自動車異動　（新）契約者住所
    private static testMethod void SearchTest_AutomobileTransfers() {
        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = [SELECT Name FROM Account LIMIT 1].Id;
        ca1.contactId = [SELECT Name FROM Contact LIMIT 1].Id;
        ca1.counterparty_Kana__c = 'テスト入電者カナ９';
        ca1.ChangeOfSubscriberInformation__c ='有'; //契約者情報変更の有無
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('AutomobileTransfers').getRecordTypeId();
        insert ca1;

        //データ取得
        List<Case> caseList = [SELECT CaseNumber FROM Case WHERE counterparty_Kana__c = 'テスト入電者カナ９'];

        PageReference pageRef = Page.AddressSearchPage;
        Test.setCurrentPage(pageRef);

        //初期化
        ApexPages.StandardController stdCon = new ApexPages.StandardController(caseList[0]);
        AddressSearchController ctrl = new AddressSearchController(stdCon) ;

        //対象項目の選択リスト
        List<SelectOption> targetField = ctrl.SelectTargetFields;

        //対象項目の選択
        ctrl.TargetField = 'SubscribersAddressAfterChange1__c'; //（新）契約者住所
        //次へボタン
        ctrl.goInsert();
        
        //郵便番号該当あり
        ctrl.PostCode = '1500011';
        List<SelectOption> AddressMaster = ctrl.SelectAddressMasters;
        ctrl.goSearch();

        //住所を選択して登録
        ctrl.UniqueKey = '1500011東京都渋谷区東１丁目';
        ctrl.confirm();
    }
}