force-app/main/default/objects/Account/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>備考</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <label>代理店</label>
</RecordType>

force-app/main/default/objects/Case/fields/counterparty_Kana__c.field-meta.xml
<CustomField>
    <fullName>counterparty_Kana__c</fullName>
    <label>入電者カナ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InquiryDetails__c.field-meta.xml
<CustomField>
    <fullName>InquiryDetails__c</fullName>
    <label>問い合わせ詳細（対応依頼用）</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReferenceAccount__c.field-meta.xml
<CustomField>
    <fullName>ReferenceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>代理店名</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>代理店</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>郵便局</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>カスタマーセンターコールデータ_代理店</relationshipLabel>
    <relationshipName>R_Account_Case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>対応依頼票転記内容</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/GeneralPurpose.recordType-meta.xml
<RecordType>
    <fullName>GeneralPurpose</fullName>
    <active>true</active>
    <businessProcess>汎用</businessProcess>
    <label>汎用</label>
</RecordType>

force-app/main/default/classes/CaseCommentTriggerTests.cls
@isTest
public class CaseCommentTriggerTests { 
	@testSetup
    static void caseSetup() {
        //Account
        account a1 = new Account();
        a1.Name = 'N0000001';
        a1.PhoneNumber__c = '1234567890';
        a1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agent').getRecordTypeId();
        insert a1;

        //Contact
        Contact con1 = new Contact();
        con1.AccountId = a1.Id;
        con1.FirstName = '太郎';
        con1.LastName = 'テスト';
        con1.PhoneNumber__c = '1234567890';
        insert con1;

        //Case
        Case ca1 = new Case();
        ca1.ReferenceAccount__c = a1.Id;
        ca1.contactId = con1.Id;
        ca1.counterparty_Kana__c = 'テストカナ１';
        ca1.InquiryDetails__c = 'テスト問い合わせ詳細';
        ca1.Remarks__c = 'テスト対応依頼票転記内容あいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくえこあいうえおかきくけこ';
        ca1.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('GeneralPurpose').getRecordTypeId();
        insert ca1;

    }
    @isTest
    private static void CaseCommentTests() {
        //データ取得
        List<Case> caseList = [SELECT id, CaseNumber FROM Case LIMIT 1];
        Case ca1 = caseList.get(0);
        CaseComment comment1 = new CaseComment(ParentId = ca1.Id, CommentBody = 'comment\n');
        insert comment1;
        comment1.CommentBody = 'comment2\n';
        update comment1;
    }
}