force-app/main/default/objects/AccidentReception_CallData__c/AccidentReception_CallData__c.object-meta.xml
<CustomObject>
    <label>事故受付_コールデータ</label>
    <nameField>
        <label>入電者名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccidentReception_CallData__c/fields/BedoreSessionID__c.field-meta.xml
<CustomField>
    <fullName>BedoreSessionID__c</fullName>
    <externalId>true</externalId>
    <label>BedoreセッションID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/IncomingCallDay__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallDay__c</fullName>
    <label>第一報入電日</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/IncomingCallDayAuto__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallDayAuto__c</fullName>
    <formula>IF ( AND (  DATEVALUE(CreatedDate)  &gt;= DATE (1868,09,08), DATEVALUE(CreatedDate) &lt;= DATE (1912,07,29)), &quot;M&quot; &amp; TEXT ( YEAR ( DATEVALUE(CreatedDate) ) - 1867 ) &amp; &quot;/&quot; &amp; TEXT ( MONTH ( DATEVALUE(CreatedDate) )) &amp; &quot;/&quot; &amp; TEXT ( DAY ( DATEVALUE(CreatedDate) )) , IF ( AND ( DATEVALUE(CreatedDate) &gt;= DATE (1912,07,30), DATEVALUE(CreatedDate) &lt;= DATE (1926,12,24)), &quot;T&quot; &amp; TEXT ( YEAR ( DATEVALUE(CreatedDate) ) - 1911) &amp; &quot;/&quot; &amp; TEXT ( MONTH ( DATEVALUE(CreatedDate) )) &amp; &quot;/&quot; &amp; TEXT ( DAY ( DATEVALUE(CreatedDate) )) , IF ( AND ( DATEVALUE(CreatedDate) &gt;= DATE (1926,12,25), DATEVALUE(CreatedDate) &lt;= DATE (1989,01,07)), &quot;S&quot; &amp; TEXT ( YEAR ( DATEVALUE(CreatedDate) ) - 1925 ) &amp; &quot;/&quot; &amp; TEXT ( MONTH ( DATEVALUE(CreatedDate))) &amp; &quot;/&quot; &amp; TEXT ( DAY ( DATEVALUE(CreatedDate) )) , IF ( AND ( DATEVALUE(CreatedDate)  &gt;= DATE (1989,01,08), DATEVALUE(CreatedDate) &lt;= DATE (2019,04,30)), &quot;H&quot; &amp; TEXT ( YEAR ( DATEVALUE(CreatedDate) ) - 1988 ) &amp; &quot;/&quot; &amp; TEXT ( MONTH ( DATEVALUE(CreatedDate) )) &amp; &quot;/&quot; &amp; TEXT ( DAY ( DATEVALUE(CreatedDate) )) , IF ( DATEVALUE(CreatedDate) &gt;= DATE (2019,05,01), &quot;R&quot; &amp; TEXT ( YEAR ( DATEVALUE(CreatedDate) ) - 2018) &amp; &quot;/&quot; &amp; TEXT ( MONTH ( DATEVALUE(CreatedDate) )) &amp; &quot;/&quot; &amp; TEXT ( DAY ( DATEVALUE(CreatedDate) )) , &quot;&quot;)))))</formula>
    <label>第一報入電日（自動）</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/IncomingCallTime__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallTime__c</fullName>
    <label>第一報入電時間</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CallDataTriggerController.cls
public class CallDataTriggerController {
    
        public CallDataTriggerController(boolean isExecuting, integer size){
            
        }
    	//ChangeData
        public void ChangeData(AccidentReception_CallData__c newCallData){
            Datetime myDate = Datetime.now();
            String strConvertedDate = myDate.format('yyyy/MM/dd/HH:mm', 'Asia/Tokyo');
            system.debug(strConvertedDate);
        	PostingDate au = new PostingDate();
			
        	newCallData.IncomingCallDay__c = au.Posting(strConvertedDate);
            newCallData.IncomingCallTime__c = au.PostingTime(strConvertedDate);
        }
    
    //OnBeforeInsert
    public void OnBeforeInsert(AccidentReception_CallData__c[] newCallDatas){
        for(AccidentReception_CallData__c newCallData : newCallDatas){
            system.debug(newCallData.IncomingCallDayAuto__c);
            system.debug(newCallData.IncomingCallDay__c);
            if(string.isBlank(newCallData.BedoreSessionID__c)){
                ChangeData(newCallData);
            }else{
                if(String.isBlank(newCallData.Name)){
                    newCallData.Name = 'フメイ';
                }
            }
        }
    }

}