force-app/main/default/objects/AccidentReception_CallData__c/AccidentReception_CallData__c.object-meta.xml
<CustomObject>
    <label>事故受付_コールデータ</label>
    <nameField>
        <label>入電者名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccidentReception_CallData__c/fields/ContractorName__c.field-meta.xml
<CustomField>
    <fullName>ContractorName__c</fullName>
    <label>契約者名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>携帯</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AccidentReception_Management__c/AccidentReception_Management__c.object-meta.xml
<CustomObject>
    <label>事故受付・伝言管理</label>
    <nameField>
        <label>受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccidentReception_Management__c/fields/ContractorName__c.field-meta.xml
<CustomField>
    <fullName>ContractorName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>コールデータ情報</label>
    <referenceTo>AccidentReception_CallData__c</referenceTo>
    <relationshipLabel>事故受付・伝言管理</relationshipLabel>
    <relationshipName>Contact_Manegement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccidentReception_Management__c/fields/ContractorNameInput1__c.field-meta.xml
<CustomField>
    <fullName>ContractorNameInput1__c</fullName>
    <label>契約者名①</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_Management__c/fields/OutputFileList__c.field-meta.xml
<CustomField>
    <fullName>OutputFileList__c</fullName>
    <label>出力ファイル一覧</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AccidentReception_Management__c/fields/PrintForm__c.field-meta.xml
<CustomField>
    <fullName>PrintForm__c</fullName>
    <label>帳票種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>事故受付（傷害）</fullName>
            </value>
            <value>
                <fullName>事故受付（賠償）</fullName>
            </value>
            <value>
                <fullName>事故受付（物損）</fullName>
            </value>
            <value>
                <fullName>事故受付（携行品/用品）</fullName>
            </value>
            <value>
                <fullName>事故受付（第三分野）</fullName>
            </value>
            <value>
                <fullName>事故受付（ヨット）</fullName>
            </value>
            <value>
                <fullName>事故受付（日整連）</fullName>
            </value>
            <value>
                <fullName>事故受付（その他）</fullName>
            </value>
            <value>
                <fullName>伝言</fullName>
            </value>
            <value>
                <fullName>雑件</fullName>
            </value>
            <value>
                <fullName>代理店契約内容照会カード</fullName>
                <isActive>false</isActive>
                <label>代理店契約内容照会カード</label>
            </value>
            <value>
                <fullName>伝言カード</fullName>
                <isActive>false</isActive>
                <label>伝言カード</label>
            </value>
            <value>
                <fullName>傷害</fullName>
                <isActive>false</isActive>
                <label>傷害</label>
            </value>
            <value>
                <fullName>傷害以外</fullName>
                <isActive>false</isActive>
                <label>傷害以外</label>
            </value>
            <value>
                <fullName>地震</fullName>
                <isActive>false</isActive>
                <label>地震</label>
            </value>
            <value>
                <fullName>契約内容相違連絡票</fullName>
                <isActive>false</isActive>
                <label>契約内容相違連絡票</label>
            </value>
            <value>
                <fullName>日整連事故受付票</fullName>
                <isActive>false</isActive>
                <label>日整連事故受付票</label>
            </value>
            <value>
                <fullName>浜のヨット・モーターボート保険事故受付票</fullName>
                <isActive>false</isActive>
                <label>浜のヨット・モーターボート保険事故受付票</label>
            </value>
            <value>
                <fullName>現場急行サービス出動依頼書</fullName>
                <isActive>false</isActive>
                <label>現場急行サービス出動依頼書</label>
            </value>
            <value>
                <fullName>第三分野商品事故受付票</fullName>
                <isActive>false</isActive>
                <label>第三分野商品事故受付票</label>
            </value>
            <value>
                <fullName>補記</fullName>
                <isActive>false</isActive>
                <label>補記</label>
            </value>
            <value>
                <fullName>風水災</fullName>
                <isActive>false</isActive>
                <label>風水災</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccidentReception_Management__c/fields/ProductDetails__c.field-meta.xml
<CustomField>
    <fullName>ProductDetails__c</fullName>
    <label>商品内容</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>自動車</fullName>
            </value>
            <value>
                <fullName>火災新種</fullName>
            </value>
            <value>
                <fullName>安心倶楽部</fullName>
            </value>
            <value>
                <fullName>窓販・標準傷害（信金）</fullName>
            </value>
            <value>
                <fullName>窓販・標準傷害（信組）</fullName>
            </value>
            <value>
                <fullName>窓販・シニア</fullName>
            </value>
            <value>
                <fullName>窓販・その他</fullName>
            </value>
            <value>
                <fullName>定期積金</fullName>
            </value>
            <value>
                <fullName>テレマ</fullName>
            </value>
            <value>
                <fullName>ダイレクトメール</fullName>
            </value>
            <value>
                <fullName>コープおすすめ</fullName>
            </value>
            <value>
                <fullName>ユーコープこども</fullName>
            </value>
            <value>
                <fullName>あんしん生活</fullName>
            </value>
            <value>
                <fullName>農業大学校・農業共済</fullName>
            </value>
            <value>
                <fullName>大学生協国旅・行事</fullName>
            </value>
            <value>
                <fullName>日整連</fullName>
            </value>
            <value>
                <fullName>学賠</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>ユーコープこどお</fullName>
                <isActive>false</isActive>
                <label>ユーコープこどお</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InputCheck__c/InputCheck__c.object-meta.xml
<CustomObject>
    <label>入力チェック</label>
    <nameField>
        <label>対象項目日本語名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InputCheck__c/fields/InputItemAPIName__c.field-meta.xml
<CustomField>
    <fullName>InputItemAPIName__c</fullName>
    <label>対象項目名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InputCheck__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>文字数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerTest.cls
@isTest
private class ContentDocumentLinkTriggerTest {
    public static AccidentReception_Management__c managementObj;
    public static InputCheck__c inputchkObj;

    @isTest static void ContentDocumentTestforFiles(){ 
        // test start
		try{        
        	AccidentReception_CallData__c calldata = new AccidentReception_CallData__c(Name = 'トランス') ;
            insert calldata;
                            
            List<AccidentReception_Management__c> managements = new List<AccidentReception_Management__c>();
            AccidentReception_Management__c managementObj = new AccidentReception_Management__c(
            	ContractorName__c = calldata.id,
                ContractorNameInput1__c = '契約者①',
                PrintForm__c = '伝言',
                ProductDetails__c = 'テレマ',
                OutputFileList__c = 'ファイルネーム1,ファイルネーム2'
            );
            insert managementObj;
            
            ContentVersion contentVersion = new ContentVersion(
            	Title = 'Penguins',
            	PathOnClient = 'Penguins.pdf',
            	VersionData = Blob.valueOf('Test Content'),
            	IsMajorVersion = true
            );
            insert contentVersion;
            
            List<ContentDocument> documents = [
                SELECT Id, Title, LatestPublishedVersionId 
                FROM ContentDocument
            ];

            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            	cdl.LinkedEntityId = managementObj.id;
            	cdl.ContentDocumentId = documents[0].Id;
            insert cdl;
            delete cdl;
            
            //insert 
            Test.startTest();
            Test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    
	@isTest static void ContentDocumentforFile(){
       
		try{
            
			AccidentReception_CallData__c calldata = new AccidentReception_CallData__c(
            	MobilePhone__c = '03-1234-5678',
                Name = 'トランス');
            insert calldata;
            
            List<InputCheck__c> inputChk = new List<InputCheck__c>();
            InputCheck__c inputChkobj = new InputCheck__c(
            	Name = '契約者名①',
                InputItemAPIName__c = 'ContractorNameInput1__c',
                Size__c=13) ;
            insert inputChkobj;
                        
            List<AccidentReception_Management__c> managements = new List<AccidentReception_Management__c>();
            AccidentReception_Management__c managementObj = new AccidentReception_Management__c(
                ContractorName__c = calldata.id,
                ContractorNameInput1__c = '契約者①',
                PrintForm__c = '伝言',
                ProductDetails__c = 'テレマ',
                OutputFileList__c = 'ファイルネーム1'
            );
            insert managementObj;
            
            ContentVersion contentVersion = new ContentVersion(
            	Title = 'Penguins',
            	PathOnClient = 'Penguins.pdf',
            	VersionData = Blob.valueOf('Test Content'),
            	IsMajorVersion = true
            );
            insert contentVersion;

            
            List<ContentDocument> documents = [
                SELECT Id, Title, LatestPublishedVersionId 
                FROM ContentDocument
            ];

            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = managementObj.id;
            cdl.ContentDocumentId = documents[0].Id;
            insert cdl;
            delete cdl;
            
            Test.startTest();
            Test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    
     @isTest static void ContentDocumentTestforBlank(){
       
        try{
            
            AccidentReception_CallData__c calldata = new AccidentReception_CallData__c(Name = 'トランス') ;
            insert calldata;
            
            List<InputCheck__c> inputChk = new List<InputCheck__c>();
            InputCheck__c inputChkobj = new InputCheck__c(
                						Name = '契約者名①' ,
                                        InputItemAPIName__c = 'ContractorNameInput1__c',
                                        Size__c=13) ;
            insert inputChkobj;
                        
            List<AccidentReception_Management__c> managements = new List<AccidentReception_Management__c>();
            AccidentReception_Management__c managementObj = new AccidentReception_Management__c(
                ContractorName__c = calldata.id,
                ContractorNameInput1__c = '契約者①',
                PrintForm__c = '伝言',
                ProductDetails__c = 'テレマ',
                OutputFileList__c = ''
            );
            insert managementObj;
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.pdf',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
            insert contentVersion;

            
            List<ContentDocument> documents = [
                SELECT Id, Title, LatestPublishedVersionId 
                FROM ContentDocument
            ];

            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = managementObj.id;
            cdl.ContentDocumentId = documents[0].Id;
            insert cdl;
            delete cdl;
            
            
            //insert 
            Test.startTest();
            Test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    @isTest static void ContentDocumentTestreturn(){
       
        try{
            
            AccidentReception_CallData__c calldata = new AccidentReception_CallData__c(Name = 'トランス') ;
            insert calldata;
            
            List<InputCheck__c> inputChk = new List<InputCheck__c>();
            InputCheck__c inputChkobj = new InputCheck__c(
                						Name = '契約者名①' ,
                                        InputItemAPIName__c = 'ContractorNameInput1__c',
                                        Size__c=13) ;
            insert inputChkobj;
                        
            List<AccidentReception_Management__c> managements = new List<AccidentReception_Management__c>();
            AccidentReception_Management__c managementObj = new AccidentReception_Management__c(
                ContractorName__c = calldata.id,
                ContractorNameInput1__c = '契約者①',
                PrintForm__c = '伝言',
                ProductDetails__c = 'テレマ',
                OutputFileList__c = ''
            );
            insert managementObj;
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.pdf',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
            insert contentVersion;

            
            List<ContentDocument> cd = [
                SELECT Id, Title, LatestPublishedVersionId 
                FROM ContentDocument
            ];

            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = managementObj.id;
            cdl.ContentDocumentId = cd[0].Id;
            insert cdl;
            delete cdl;


            
            
            //insert 
            Test.startTest();
            Test.stopTest();
            
        }
        catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
}