force-app/main/default/objects/AccidentReception_CallData__c/AccidentReception_CallData__c.object-meta.xml
<CustomObject>
    <label>事故受付_コールデータ</label>
    <nameField>
        <label>入電者名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccidentReception_CallData__c/fields/AccidentDate__c.field-meta.xml
<CustomField>
    <fullName>AccidentDate__c</fullName>
    <label>事故日</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/CallerContactInformation1__c.field-meta.xml
<CustomField>
    <fullName>CallerContactInformation1__c</fullName>
    <label>入電者の連絡先</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/CallerContactInformation2__c.field-meta.xml
<CustomField>
    <fullName>CallerContactInformation2__c</fullName>
    <label>入電者の連絡先２</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/ContractorName__c.field-meta.xml
<CustomField>
    <fullName>ContractorName__c</fullName>
    <label>契約者名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/IncomingCallDay__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallDay__c</fullName>
    <label>第一報入電日</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/IncomingCallTime__c.field-meta.xml
<CustomField>
    <fullName>IncomingCallTime__c</fullName>
    <label>第一報入電時間</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>携帯</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>証券番号</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/RegisteredPhoneNumber1__c.field-meta.xml
<CustomField>
    <fullName>RegisteredPhoneNumber1__c</fullName>
    <label>登録の電話番号</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/RegisteredPhoneNumber2__c.field-meta.xml
<CustomField>
    <fullName>RegisteredPhoneNumber2__c</fullName>
    <label>登録の電話番号２</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/AccidentReception_CallData__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>入電者と契約者の関係</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccidentReception_Management__c/AccidentReception_Management__c.object-meta.xml
<CustomObject>
    <label>事故受付・伝言管理</label>
    <nameField>
        <label>受付番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccidentReception_Management__c/fields/AccidentDate__c.field-meta.xml
<CustomField>
    <fullName>AccidentDate__c</fullName>
    <label>事故日</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>事故の事故日に同じ</fullName>
            </value>
            <value>
                <fullName>フリー入力</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccidentReception_Management__c/fields/ContractorName__c.field-meta.xml
<CustomField>
    <fullName>ContractorName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>コールデータ情報</label>
    <referenceTo>AccidentReception_CallData__c</referenceTo>
    <relationshipLabel>事故受付・伝言管理</relationshipLabel>
    <relationshipName>Contact_Manegement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <label>証券番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateManagementControllerTests.cls
@isTest
private class CreateManagementControllerTests {
    public static AccidentReception_Management__c app;

    @isTest static void managementCaseTest1(){
       
        // test start
        try{
            AccidentReception_CallData__c contact = new AccidentReception_CallData__c(
                MobilePhone__c = '03-1234-5678' ,
                Name = 'トランス',
                ContractorName__c='aa', AccidentDate__c = 'R3/1/1',
                PolicyNumber__c='266262-111', IncomingCallTime__c = '22:22',
                IncomingCallDay__c = 'R2/12/11', RegisteredPhoneNumber1__c = '151551',
                Relationship__c = 'aa', CallerContactInformation1__c = '111',
                RegisteredPhoneNumber2__c = '111',
                CallerContactInformation2__c = '22') ;
            insert contact;

            CreateManagementController.managementCase(System.label.TypeFireRecordType, contact.Id);
            
        }catch(Exception e){
            system.debug('e.getMessage():'+e.getDmlFieldNames(0));
        }
    }
    
}