force-app/main/default/objects/User/fields/OnlineID__c.field-meta.xml
<CustomField>
    <fullName>OnlineID__c</fullName>
    <label>代理店オンラインID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/OnlinePW__c.field-meta.xml
<CustomField>
    <fullName>OnlinePW__c</fullName>
    <label>代理店オンラインPW</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OnlineSearchFormController.cls
public with sharing class OnlineSearchFormController{

    @AuraEnabled(cacheable=true)
    public static List<User> getUserOnlineInfo(){

        String userId = userinfo.getUserId();

        List<User> users= [
                SELECT
                    Id,
                    OnlineId__c , OnlinePW__c
                FROM
                    User
                WHERE
                    Id = :userId
                LIMIT 1
        ];

        return users;
    }

}